{% set name = "git-annex" %}

#
# This recipe builds two variants of the git-annex conda package: the standard one, and a "nodep" (no-dependencies)
# one.  The nodep package installs the standalone version of git-annex (
# https://git-annex.branchable.com/install/Linux_standalone/ ), which has no dependencies; it can be used to install
# git-annex into conda environments that include packages which conflict with some dependencies of git-annex.  The
# standard (non-nodep) version is preferred; the nodep version should only be used in case of unresolvable dependency
# conflicts.

#
# The standalone build is currently taken from the autobuilder run by git-annex' author, as ready-made binaries.
# Better would be to build it as part of the conda-forge packaging process, but the current sources are designed to
# be built on a Debian distribution, which conda-forge does not use.
#

#
# The version number printed by the standalone (nodep) version is typically behind the version number of 
# the standard version, but in practice has the same functionality -- see discussion here:
# https://git-annex.branchable.com/forum/standalone_tarballs_for_specific_versions/#comment-d15b771fb5d23ce0c8dfb7f1c25064c5
#
{% set version = "10.20250320" %}  # [not nodep]
{% set version = "10.20250320" %}  # [nodep]
{% set version_printed = version %}  # [not nodep]
{% set version_printed = "10.20250320-g74457b6b93fd448964ceae28f2712678f732b4d6" %}  # [nodep]

{% set sha256 = "b1c426ba737291d1e432d5062784ecd25fc14a48407e030d34c48ceed40a5a0e" %}  # [not nodep]
{% set sha256 = "58aadf91f6b05a8ed9fb6a351d5e786da9fe1890e202b9b935d18e876caf25a1" %}  # [nodep]
{% set size = "62052170" %}  # [nodep]

{% set nodep = True %}  # [nodep]
{% set nodep = False %}  # [not nodep]

{% set build = 0 %}
# prioritize non-nodep variant via build number
{% if not nodep %}
{% set build = build + 100 %}
{% endif %}

#
# This recipe builds GHC, the Haskell compiler used to compile git-annex, from source, then uses it
# to compile git-annex.  It would be better to separate GHC into its own conda-forge package, and have the
# git-annex recipe depend on that, but I could not make that work.  Hopefully, someone with a better
# understanding of ghc and conda-forge can eventually rewrite the recipes in the more proper way.
#
# For related discussions see
# https://github.com/conda-forge/git-annex-feedstock/pull/44
# https://github.com/bioconda/bioconda-recipes/pull/16008
#

#
# We currently do a two-stage boostrap:
#   (note: ghc_bootstrap_version, ghc_src_version and ghc_src2_version are jinja2 variables defined below)
#   - use binary distribution of GHC ghc_bootstrap_version to compile from source GHC ghc_src_version
#   - use GHC ghc_src_version to compile GHC ghc_src2_version
#   - use GHC ghc_src2_version to compile git-annex
# This approach is needed because the only GHC version whose binary distribution seems compatible
# with the conda-forge build environment is ghc_bootstrap_version, and that version is much too old to
# build git-annex with.

# ghc_src2_version must correspond to the ghc version of the LTS Haskell version specified in the
# resolver: line in stack.yaml file which is at the root of the git-annex source archive.
# E.g. for resolver: lts-18.13 the ghc version given at https://www.stackage.org/lts-18.13 is 8.10.7
{% set ghc_src2_version = "8.10.7" %}
{% set ghc_src2_sha256 = "e3eef6229ce9908dfe1ea41436befb0455fefb1932559e860ad4c606b0d03c9d" %}

# ghc_src_version must be recent enough to compile ghc_src2_version.
# E.g. for ghc_src2_version 8.10.7, the page at https://www.haskell.org/ghc/download_ghc_8_10_7.html#sources
# says ghc_src_version must be at least 8.6
{% set ghc_src_version = "8.8.4" %}
{% set ghc_src_sha256 = "f0505e38b2235ff9f1090b51f44d6c8efd371068e5a6bb42a2a6d8b67b5ffc2d" %}

# ghc_bootstrap_version must be recent enough to compile ghc_src_version.
# E.g. for ghc_src_version 8.8.4, the page at https://www.haskell.org/ghc/download_ghc_8_8_4.html#sources
# says ghc_boostrap_version must be at least 8.4
{% set ghc_bootstrap_version = "8.4.2" %}
{% set ghc_bootstrap_linux_sha256 = "28c31489ed9a83af4400685ec8bc72a6d43d08958d75b2dc35d29a894a5c9d93" %}

package:
  name: {{ name }}
  version: {{ version }}

{% if not nodep %}
source:
  - url: https://hackage.haskell.org/package/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: git_annex_main
    patches:
      - 0001-add-fdo-notify.patch

  - url: https://downloads.haskell.org/~ghc/{{ ghc_bootstrap_version }}/ghc-{{ ghc_bootstrap_version }}-x86_64-centos67-linux.tar.xz  # [linux]
    sha256: {{ ghc_bootstrap_linux_sha256 }}  # [linux]
    folder: ghc_bootstrap  # [linux]

  - url: https://downloads.haskell.org/~ghc/{{ ghc_src_version }}/ghc-{{ ghc_src_version }}-src.tar.xz
    sha256: {{ ghc_src_sha256 }}
    folder: ghc_src

  - url: https://downloads.haskell.org/~ghc/{{ ghc_src2_version }}/ghc-{{ ghc_src2_version }}-src.tar.xz
    sha256: {{ ghc_src2_sha256 }}
    folder: ghc_src2

build:
  number: {{ build }}
  skip: True  # [not linux]
  string: "alldep_h{{ PKG_HASH }}_{{ build }}"  # [not nodep]
  script: ${RECIPE_DIR}/build_nodepFalse.sh
  # Tracked features also de-prioritize that build
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#track-features
  # and we want to de-prioritize standalone build (it is slower etc)
  track_features:
    - standalone  # [nodep]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - binutils
    - bzip2
    - coreutils
    - findutils
    - gmp
    - libffi
    - libtool
    - libxml2
    - make
    - ncurses
    - perl
    - pkg-config
    - stack
    - xz
  host:
    - dbus
    - gmp
    - libffi
    - libiconv
    - libmagic
    - lsof
    - ncurses
    - openssh
    - rsync
    - sqlite
    - zlib
  run:
    - curl
    - git >=2.22
    - gnupg >=2.1.1
    - lsof
    - openssh
    - rsync
{% endif %}

{% if nodep %}
source:
  - url: http://archive.org/download/git-annex-builds/SHA256E-s{{ size }}--{{ sha256 }}.tar.gz
#  - url: https://downloads.kitenet.net/git-annex/autobuild/amd64/git-annex-standalone-amd64.tar.gz 
    sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # [not linux]
  string: "nodep_h{{ PKG_HASH }}_{{ build }}"
  script: ${RECIPE_DIR}/build_nodepTrue.sh
  ignore_prefix_files: True
  detect_binary_files_with_prefix: False
  binary_relocation: False

requirements:
  run_constrained:
    - gnupg >=2.1.1
{% endif %}

test:
  requires:
    - gnupg >=2.1.1
  commands:
    - git-annex version | grep {{ version_printed }}
    - git-annex test
  downstreams:
    - annexremote

about:
  home: https://git-annex.branchable.com
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: A tool for managing large files with git
  description: |
    git-annex allows managing files with git, without checking the file contents into git.
    It is useful when dealing with files larger than git can currently easily handle.
    The contents can be stored locally or in various remote repositories; git-annex tracks
    which contents is stored where.
  doc_url: https://git-annex.branchable.com
  dev_url: http://source.git-annex.branchable.com/?p=source.git;a=summary

extra:
  recipe-maintainers:
    - notestaff
    - yarikoptic
    - joeyh
